[package]
name = "rs_taskflow_derive"
version = "0.1.0"
authors = ["Miaofei <ameision@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = "1.0.73"

[dev-dependencies]
rs_taskflow = { path = "../rs_taskflow" }
