[package]
name = "rs_taskflow_derive"
version = "0.1.0"
authors = ["Miaofei <ameision@hotmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.54"
quote = "1.0.26"
syn = { version = "2.0.13", features = ["extra-traits"] }
