[package]
name = "rs_taskflow"
version = "0.1.0"
authors = ["Miaofei <ameision@hotmail.com>"]
edition = "2018"

[dependencies]
rs_taskflow_derive = { path = "../rs_taskflow_derive" }
tokio = { version = "1.7.1", features = ["rt-multi-thread", "macros"] }

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[[test]]
name = "flow_test"
path = "tests/flow_test.rs"
